# -*- coding: utf-8 -*-
"""Projeto Python - Equipe 10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ml3e1RxCy8W6vi1pFIWTTbP2KWCWysFV
"""

'''Programa de compras de uma loja de informática
SoulCode Academy - Turma BC12 - Equipe 10
- João Victor Barboza Rodrigues
- Malu Caires Souza
- Marcelo Ferreira de Armando
- Taraneh de Paula Nascimento'''

# Declaração de listas e variáveis para nosso sistema:

produtos = ['Teclado com fio', 'Teclado sem fio', 'Mouse com fio', 'Mouse sem fio', 'Pen Drive 32GB', 'Pen Drive 64GB', 'Memória RAM 2GB DDR2', 'Memória RAM 8GB DDR4', 'Cabo de Vídeo VGA', 'Cabo de Vídeo HDMI', 'Monitor 17"', 'Monitor 22"']
valor_produtos = [70, 110, 40, 70, 35, 70, 50, 230, 40, 50, 480, 890]

servicos = [ 'Formatação', 'Manutenção', 'Limpeza e pasta térmica', 'Instalação de programas ', 'Configuração de rede e impressora', 'Xerox (por folha)', 'Impressão (por folha)']
valor_servicos = [150, 200, 80, 50, 50, 1, 2]

carrinho_prod = []
carrinho_prod_quant = []
carrinho_prod_valor_total = []

carrinho_serv = []
carrinho_serv_quant = []
carrinho_serv_valor_total = []

soma_total = 0
soma_total_prod = 0
soma_total_serv = 0
compra_finalizada = 0

# Tela inicial do sistema:
while True:
  #menu de entrada no sistema da loja com validação de entrada de dados
  print("*** SOULTECH - TECNOLOGIA AO SEU ALCANCE *** \n                *** Bem-vindo! ***")
  print("")
  op1 = input("Digite A para acessar nosso sistema. \nDigite F para finalizar:\n")
  
  if op1 != "A" and op1 != "F":
    print("Opção inválida!")
    continue

  #finalizar sistema (opção F)
  elif op1 == "F": 
    print("Agradecemos a visita!")
    print("")
    break

  #continuar sistema (opção A) e menu inicial
  else:
    while True:
      print('''          *** MENU INICIAL ***
      [1] - Adicionar Produto
      [2] - Adicionar Serviço
      [3] - Ver carrinho
      [4] - Finalizar Compra
      [5] - Cancelar Compra''')
      op2 = int(input("Digite a opção desejada:\n"))

      print("")

      #Opção 1 - Adicionar Produto
      if op2 == 1:
        while True:
          #Lista de Produtos e Valores
          print("Lista de produtos:")
          print(f"[0] - Voltar ao menu inicial")
          for i in range(0, len(produtos)):
            print(f"[{i+1}] - {produtos[i]} - R$ {float(valor_produtos[i]):.2f}")
          print("")
          
          #Seleção do produto pelo usuário (variável escolha) e validação da opção
          escolha = int(input("Digite o número correspondente ao produto que deseja ou 0 para sair: "))
          while escolha > 12 or escolha < 0:
            escolha = int(input("Número inválido. Digite o número correspondente ao produto que deseja: "))
          if escolha == 0:
            break
    
          #Confirmação do produto e definição da quantidade pelo usuário com validação de quantidade
          print (f"Você selecionou o produto {produtos[escolha-1]} de valor R$ {float(valor_produtos[escolha-1]):.2f}")
          quant = int(input("Informe a quantidade ou digite 0 para selecionar outro produto: "))
          if quant > 0:
            carrinho_prod.append(produtos[escolha-1])
            carrinho_prod_quant.append(quant)
            carrinho_prod_valor_total.append(quant * valor_produtos[escolha-1])
            print(f"{quant} unidade(s) do produto {produtos[escolha-1]} foi(foram) adicionado(s) ao carrinho. Valor unitário do produto: R$ {float(valor_produtos[escolha-1]):.2f}. Valor total: R$ {float(quant*valor_produtos[escolha-1]):.2f}")
            while True:
              p = int(input("Deseja adicionar mais produtos ao carrinho? \n[1] - Sim \n[2] - Não\n"))
              if p > 2 or p < 1:
                print("Opção inválida! Digite novamente.")
              else:
                break
            if p == 1:
              continue
            else:
              break
          elif quant == 0:
            print("Selecione outro produto")
            continue
          elif quant < 0:
            print("A quantidade informada não é válida. O produto não foi adicionado ao carrinho. Selecione outro produto")
            continue

      #Opção 2 - Adicionar Serviço
      elif op2 == 2:
        #Lista de Serviços e Valores
        while True:
          #Seleção do produto pelo usuário (variável escolha) e validação da opção
          print("Lista de serviços:")
          print(f"[0] - Voltar ao menu inicial")
          for i in range(0, len(servicos)):
            print(f"[{i+1}] - {servicos[i]} - R$ {valor_servicos[i]:.2f}:")
          print("")

          #Seleção do produto pelo usuário (variável escolha) e validação da opção
          escolha = int(input("Digite o número correspondente ao serviço que deseja ou 0 para sair: "))
          while escolha > 7 or escolha < 0:
            escolha = int(input("Número inválido. Digite o número correspondente ao serviço que deseja: "))
          if escolha == 0:
            break
        
          #Confirmação do produto e definição da quantidade pelo usuário com validação de quantidade
          print (f"Você selecionou o serviço {servicos[escolha-1]} de valor R$ {valor_servicos[escolha-1]:.2f}")
          quant = int(input("Informe a quantidade ou digite 0 para selecionar outro serviço: "))
          if quant > 0:
            carrinho_serv.append(servicos[escolha-1])
            carrinho_serv_quant.append(quant)
            carrinho_serv_valor_total.append(quant * valor_servicos[escolha-1])
            print(f"{quant} unidade(s) do serviço {servicos[escolha-1]} foi(foram) adicionado(s) ao carrinho. Valor unitário do servico: R$ {valor_servicos[escolha-1]:.2f}. Valor total: R$ {(quant*valor_servicos[escolha-1]):.2f}")
            while True:
              p = int(input("Deseja adicionar mais servicos ao carrinho? \n[1] - Sim \n[2] - Não\n"))
              if p > 2 or p < 1:
                print("Opção inválida! Digite novamente.")
              else:
                break
            if p == 1:
              continue
            else:
              break
          elif quant == 0:
            print("Selecione outro serviço")
            continue
          elif quant < 0:
            print("A quantidade informada não é válida. O serviço não foi adicionado ao carrinho. Selecione outro serviço")
            continue    

      #Opção 3 - Exibir Carrinho
      elif op2 == 3:

        #Exibir o carrinho
        while True:
          print("          *** CARRINHO: *** \n")
          if len(carrinho_prod) > 0:
            print("Produtos adicionados no carrinho:")
            soma_total_prod = 0
            for i in range(0, len(carrinho_prod)):
              print(f"[{i+1}] - {carrinho_prod[i]} - Valor unitário: R$ {(carrinho_prod_valor_total[i] / carrinho_prod_quant[i]):.2f} - Quantidade: {carrinho_prod_quant[i]:.2f} - Valor total: R$ {carrinho_prod_valor_total[i]:.2f}")
              soma_total_prod += carrinho_prod_valor_total[i] 
          if len(carrinho_serv) > 0:
            print("")
            print("Serviços adicionados no carrinho:")
            soma_total_serv = 0
            for i in range(0, len(carrinho_serv)):
              print(f"[{i+1}] - {carrinho_serv[i]} - Valor unitário: R$ {(carrinho_serv_valor_total[i] / carrinho_serv_quant[i]):.2f} - Quantidade: {carrinho_serv_quant[i]} - Valor total: R$ {carrinho_serv_valor_total[i]:.2f}")
              soma_total_serv += carrinho_serv_valor_total[i]
            print("")

          #Informa o valor total da compra, caso haja algum produto ou serviço no carrinho
          if len(carrinho_prod) > 0 or len(carrinho_serv) > 0:
            soma_total = soma_total_prod + soma_total_serv
            print(f"Valor total da compra: R$ {soma_total:.2f}")
            print("")

          #Informa que o carrinho está vazio, caso não haja nenhum produto ou serviço
          else:
            print("Seu carrinho está vazio!")
            print("")

          #Opção 3 - Exibir Carrinho - Menu
          print('''Menu do carrinho:
          [1] - Alterar quantidade de um produto ou serviço
          [2] - Remover um produto ou serviço
          [3] - Desistir da compra
          [4] - Retornar ao menu inicial''')
          op_carrinho = int(input("Digite a opção desejada:\n"))

          #Opção 3.1 - Alterar quantidade de um produto ou serviço no carrinho
          if op_carrinho == 1:
            while True:
              #Opção 3.1 - Exibir menu de alteração de quantidade de produto ou serviço no carrinho
              print('''Menu do carrinho:
              [1] - Alterar quantidade de um produto?
              [2] - Alterar quantidade de um serviço?
              [3] - Retornar ao menu anterior''')
              op_carrinho_op1 = int(input("Digite a opção desejada:\n"))

              #Opção 3.1.1 - Alterar a quantidade de um produto no carrinho
              if op_carrinho_op1 == 1:

                #Print para mostrar o carrinho de produto:
                print("      *** CARRINHO DE PRODUTOS: *** \n")
                for i in range(0, len(carrinho_prod)):
                  print(f"[{i+1}] - {carrinho_prod[i]} - Valor unitário: R$ {(carrinho_prod_valor_total[i] / carrinho_prod_quant[i]):.2f} - Quantidade: {carrinho_prod_quant[i]} - Valor total: R$ {carrinho_prod_valor_total[i]:.2f}")

                #Definição de qual produto será alterada a quantidade
                alterar_prod = int(input("Digite qual produto deseja alterar quantidade: "))
                while alterar_prod < 0 or alterar_prod > len(carrinho_prod):
                  alterar_prod = int(input("Resposta inválida. Digite qual produto deseja alterar quantidade: "))
                
                #Input de nova quantidade
                alterar_quant_prod = int(input("Digite a nova quantidade: "))
                while 0 > alterar_quant_prod:
                  alterar_quant_prod = int(input("Resposta inválida. Digite a nova quantidade: "))

                print(f"Você irá atualizar a quantidade do produto {carrinho_prod[alterar_prod-1]} para {alterar_quant_prod} unidades.")
                sim_ou_nao = int(input("Confirma? [1] - Sim [2] - Não\n"))
                
                while True:
                  if sim_ou_nao == 1:
                    #Atualizar a quantidade:
                    valor_unitario = int(carrinho_prod_valor_total[alterar_prod-1]/(carrinho_prod_quant[alterar_prod-1]))
                    carrinho_prod_quant[alterar_prod-1] = alterar_quant_prod

                    #Atualizar o valor em dinheiro no carrinho:
                    soma_total_prod -= carrinho_prod_valor_total[alterar_prod-1]
                    carrinho_prod_valor_total[alterar_prod-1] = int(alterar_quant_prod * valor_unitario)
                    soma_total_prod += carrinho_prod_valor_total[alterar_prod-1]
                    break
                  elif sim_ou_nao == 2:
                    break
                  else:
                    sim_ou_nao = int(input("Resposta inválida. Confirma? [1] - Sim [2] - Não\n"))

              #Opção 3.1.2 - Alterar a quantidade de um serviço no carrinho
              elif op_carrinho_op1 == 2:

                #Print para mostrar o carrinho de serviço:
                print("      *** CARRINHO DE SERVIÇOS: *** \n")
                for i in range(0, len(carrinho_serv)):
                  print(f"[{i+1}] - {carrinho_serv[i]} - Valor unitário: R$ {(carrinho_serv_valor_total[i] / carrinho_serv_quant[i]):.2f} - Quantidade: {carrinho_serv_quant[i]} - Valor total: R$ {carrinho_serv_valor_total[i]:.2f}")

                #Definição de qual serviço será alterada a quantidade
                alterar_serv = int(input("Digite qual serviço deseja alterar quantidade: "))
                while alterar_serv < 0 or alterar_serv > len(carrinho_serv):
                  alterar_serv = int(input("Resposta inválida. Digite qual serviço deseja alterar quantidade: "))
                
                #Input de nova quantidade
                alterar_quant_serv = int(input("Digite a nova quantidade: "))
                while 0 > alterar_quant_serv:
                  alterar_quant_serv = int(input("Resposta inválida. Digite a nova quantidade: "))

                print(f"Você irá atualizar a quantidade do serviço {carrinho_serv[alterar_serv-1]} para {alterar_quant_serv} unidades.")
                sim_ou_nao = int(input("Confirma? [1] - Sim [2] - Não\n"))
                
                while True:
                  if sim_ou_nao == 1:
                    #Atualizar a quantidade:
                    valor_unitario = int(carrinho_serv_valor_total[alterar_serv-1]/(carrinho_serv_quant[alterar_serv-1]))
                    carrinho_serv_quant[alterar_serv-1] = alterar_quant_serv

                    #Atualizar o valor em dinheiro no carrinho:
                    soma_total_serv -= carrinho_serv_valor_total[alterar_serv-1]
                    carrinho_serv_valor_total[alterar_serv-1] = (alterar_quant_serv * valor_unitario)
                    soma_total_serv += carrinho_serv_valor_total[alterar_serv-1]
                    break
                  elif sim_ou_nao == 2:
                    break
                  else:
                    sim_ou_nao = int(input("Resposta inválida. Confirma? [1] - Sim [2] - Não\n"))

              #Opção 3.1.3 - Retornar ao menu anterior
              elif op_carrinho_op1 == 3:
                break

              #Validação do menu inicial - Opção inválida
              else:
                print("Opção inválida\n")
                continue
              break

          #Opção 3.2 - Remover um produto ou serviço no carrinho
          elif op_carrinho == 2:

            #Exibir o carrinho
            print("          *** CARRINHO: *** \n")
            if len(carrinho_prod) > 0:
              print("Produtos adicionados no carrinho:")
              soma_total_prod = 0
              for i in range(0, len(carrinho_prod)):
                print(f"[{i+1}] - {carrinho_prod[i]} - Valor unitário: R$ {(carrinho_prod_valor_total[i] / carrinho_prod_quant[i]):.2f} - Quantidade: {carrinho_prod_quant[i]} - Valor total: R$ {carrinho_prod_valor_total[i]:.2f}")
                soma_total_prod += carrinho_prod_valor_total[i] 
            if len(carrinho_serv) > 0:
              print("")
              print("Serviços adicionados no carrinho:")
              soma_total_serv = 0
              for i in range(0, len(carrinho_serv)):
                print(f"[{i+1}] - {carrinho_serv[i]} - Valor unitário: R$ {(carrinho_serv_valor_total[i] / carrinho_serv_quant[i]):.2f} - Quantidade: {carrinho_serv_quant[i]} - Valor total: R$ {carrinho_serv_valor_total[i]:.2f}")
                soma_total_serv += carrinho_serv_valor_total[i]
              print("")

            #Informa o valor total da compra, caso haja algum produto ou serviço no carrinho
            if len(carrinho_prod) > 0 or len(carrinho_serv) > 0:
              soma_total = soma_total_prod + soma_total_serv
              print(f"Valor total da compra: R$ {soma_total:.2f}")
              print("")

            #Informa que o carrinho está vazio, caso não haja nenhum produto ou serviço
            else:
              print("Seu carrinho está vazio!")

            #Opção 3.2 - Exibir menu de exclusão de produto ou serviço no carrinho
            while True:
              prod_ou_serv = int(input('''Deseja deletar produto ou serviço? 
              [1] - Produto 
              [2] - Serviço 
              [3] - Voltar o menu inicial\n'''))
              if prod_ou_serv < 1 or prod_ou_serv > 3:
                print("Opção inválida")
              else:
                break     

            #Opção 3.2.1 - Excluir um produto do carrinho 
            #Exibir carrinho de produtos
            if prod_ou_serv == 1:
              print("Produtos adicionados no carrinho:")
              for i in range(0, len(carrinho_prod)):
                print(f"[{i+1}] - {carrinho_prod[i]} - Valor unitário: {carrinho_prod_valor_total[i] / carrinho_prod_quant[i]} - Quantidade: {carrinho_prod_quant[i]} - Valor total: R$ {carrinho_prod_valor_total[i]:.2f}")

              #Escolher o produto para exclusão
              while True:
                prod_deletar = int(input("Qual produto deseja deletar?\n"))
                if prod_deletar < 1 or (prod_deletar-1) > len(carrinho_prod):
                  print("Opção inválida")
                  continue
                else:
                  print(f"Você irá deletar o produto {carrinho_prod[prod_deletar-1]}")
                  break

              #Confirmar exclusão
              while True:
                sim_ou_nao = int(input("Confirma? [1] - Sim [2] - Não\n"))
                if sim_ou_nao == 1:
                  del carrinho_prod[prod_deletar-1]
                  del carrinho_prod_quant[prod_deletar-1]
                  del carrinho_prod_valor_total[prod_deletar-1]                
                  break
                elif sim_ou_nao == 2:
                  break
                else:
                  print("Opção inválida")
              print("")
              break

            ##Opção 3.2.2 - Excluir um serviço do carrinho  
            #Exibir carrinho de serviços
            elif prod_ou_serv == 2:
              print("Serviços adicionados no carrinho:")
              for i in range(0, len(carrinho_serv)):
                print(f"[{i+1}] - {carrinho_serv[i]} - Valor unitário: {carrinho_serv_valor_total[i] / carrinho_serv_quant[i]} - Quantidade: {carrinho_serv_quant[i]} - Valor total: R$ {carrinho_serv_valor_total[i]:.2f}")

              #Escolher o serviço para exclusão
              while True:
                serv_deletar = int(input("Qual serviço deseja deletar?\n"))
                if serv_deletar < 1 or (serv_deletar-1) > len(carrinho_serv):
                  print("Opção inválida")
                  continue
                print("")
                print(f"Você irá deletar o serviço {carrinho_serv[serv_deletar-1]}")

                #Confirmar exclusão
                while True:
                  sim_ou_nao = int(input("Confirma? [1] - Sim [2] - Não\n"))
                  if sim_ou_nao == 1:
                    del carrinho_serv[serv_deletar-1]
                    del carrinho_serv_quant[serv_deletar-1]
                    del carrinho_serv_valor_total[serv_deletar-1]                
                    break
                  elif sim_ou_nao == 2:
                    break
                  else:
                    print("Opção inválida")
                print("")
                break

            #Opção 3.2.3 - Retornar ao menu anterior
            elif prod_ou_serv == 3:
              break

          #Opção 3.3 - Desistir da compra
          elif op_carrinho == 3:

            #Confirma se o usuário deseja mesmo desistir da compra
            while True:
              sim_ou_nao = int(input('''Deseja realmente desistir da sua compra?
              [1] - Sim
              [2] - Não\n'''))

              #Limpa o carrinho de produtos e serviços
              if sim_ou_nao == 1:
                carrinho_prod.clear()
                carrinho_prod_quant.clear()
                carrinho_prod_valor_total.clear()

                carrinho_serv.clear()
                carrinho_serv_quant.clear()
                carrinho_serv_valor_total.clear()
                break

              #Cancela a desistência da compra, mantendo o carrinho
              elif sim_ou_nao == 2:
                print("Obrigado por continuar comprando conosco!")
                break

              #Validação de menu
              elif sim_ou_nao < 0 or sim_ou_nao > 2:
                print("Opção inválida")

          #Opção 3.4 - Retorna ao menu inicial
          elif op_carrinho == 4:
            break

      #Opção 4 - Finalizar a compra
      elif op2 == 4:

        #Exibir o carrinho
        print("          *** CARRINHO: *** \n")
        if len(carrinho_prod) > 0:
          print("Produtos adicionados no carrinho:")
          soma_total_prod = 0
          for i in range(0, len(carrinho_prod)):
            print(f"[{i+1}] - {carrinho_prod[i]} - Valor unitário: {(carrinho_prod_valor_total[i] / carrinho_prod_quant[i]):.2f} - Quantidade: {carrinho_prod_quant[i]} - Valor total: R$ {carrinho_prod_valor_total[i]:.2f}")
            soma_total_prod += carrinho_prod_valor_total[i] 
        if len(carrinho_serv) > 0:
          print("")
          print("Serviços adicionados no carrinho:")
          soma_total_serv = 0
          for i in range(0, len(carrinho_serv)):
            print(f"[{i+1}] - {carrinho_serv[i]} - Valor unitário: {(carrinho_serv_valor_total[i] / carrinho_serv_quant[i]):.2f} - Quantidade: {carrinho_serv_quant[i]} - Valor total: R$ {carrinho_serv_valor_total[i]:.2f}")
            soma_total_serv += carrinho_serv_valor_total[i]
          print("")

        #Informa o valor total da compra, caso haja algum produto ou serviço no carrinho
        if len(carrinho_prod) > 0 or len(carrinho_serv) > 0:
          soma_total = soma_total_prod + soma_total_serv
          print(f"Valor total da compra: R$ {soma_total:.2f}")
          print("")

        #Informa que o carrinho está vazio, caso não haja nenhum produto ou serviço
        else:
          print("Opção inválida. Seu carrinho está vazio!")
          print("")

        #Seleciona o método de pagamento
        while True:
          #Valida se o carrinho não está em branco
          if soma_total == 0:
            break

          #Solicita o método de pagamento
          op_pagamento = int(input(f'''Finalização da compra!

          Escolha seu método de pagamento:
          [1] - PIX
          [2] - Cartão de débito
          [3] - Cartão de crédito
          [4] - Dinheiro\n'''))
          print("")

          if op_pagamento < 1 or op_pagamento > 4:
            print("Opção inválida!")
            print("")
          
          #Opção 4.1 - Forma de pagamento PIX
          elif op_pagamento == 1:
            print('''Você escolheu a opção PIX
            Nossa chave: xyz
            ...
            Aguarde um momento por favor
            ...''')
          
          #Opção 4.2 - Forma de pagamento Cartão de Débito
          elif op_pagamento == 2:
            print('''Você escolheu a opção cartão de débito
            Insira seu cartão
            ...
            Digite sua senha
            ...
            Aguarde um momento por favor
            ...''')
          
          #Opção 4.3 - Forma de pagamento Cartão de Crédito
          elif op_pagamento == 3:
            print('''Você escolheu a opção cartão de crédito
            Insira seu cartão
            ...
            Digite sua senha
            ...
            Aguarde um momento por favor
            ...''')
          
          #Opção 4.4 - Forma de pagamento Dinheiro
          elif op_pagamento == 4:
            print("Você escolheu a opção dinheiro")
            
            dinheiro_inserido = float(input("Informe o valor inserido para pagamento: R$ "))

            #Define o troco a ser devolvido
            while True:
              if dinheiro_inserido < soma_total:
                print("Valor insuficiente")
                dinheiro_inserido = float(input("Informe o valor inserido para pagamento: R$ "))
              else:
                troco = dinheiro_inserido - soma_total
                print(f"Seu troco será de R$ {troco:.2f}")
                cedulas = 50
                totced = 0

                while True:
                  if troco >= cedulas:
                      troco -= cedulas
                      totced += 1         
                  else:
                    if totced > 0:
                      print(f"Total de {totced} cédulas de R$ {cedulas:.2f}")
                    if cedulas == 50:
                        cedulas = 20
                    elif cedulas == 20:
                        cedulas = 10
                    elif cedulas == 10:
                        cedulas = 5
                    elif cedulas == 5:
                        cedulas = 2
                    elif cedulas == 2:
                        cedulas = 1
                    elif cedulas == 1:
                        cedulas = 0   
                    totced = 0
                    if troco == 0:
                      break 
                if troco == 0:
                  break      
            
          #Finalização da compra
          print("Compra aprovada!")
          if len(carrinho_prod) > 0:
            print("Produtos adquiridos:")
            soma_total_prod = 0
            for i in range(0, len(carrinho_prod)):
              print(f"[{i+1}] - {carrinho_prod[i]} - Valor unitário: {(carrinho_prod_valor_total[i] / carrinho_prod_quant[i]):.2f} - Quantidade: {carrinho_prod_quant[i]} - Valor total: R$ {carrinho_prod_valor_total[i]:.2f}")
              soma_total_prod += carrinho_prod_valor_total[i] 
          if len(carrinho_serv) > 0:
            print("")
            print("Serviços adquiridos:")
            soma_total_serv = 0
            for i in range(0, len(carrinho_serv)):
              print(f"[{i+1}] - {carrinho_serv[i]} - Valor unitário: {(carrinho_serv_valor_total[i] / carrinho_serv_quant[i]):.2f} - Quantidade: {carrinho_serv_quant[i]} - Valor total: R$ {carrinho_serv_valor_total[i]:.2f}")
              soma_total_serv += carrinho_serv_valor_total[i]
            print("")

          #Informa o valor total da compra
          if len(carrinho_prod) > 0 or len(carrinho_serv) > 0:
            soma_total = soma_total_prod + soma_total_serv
            print(f"Valor total da compra: R$ {soma_total:.2f}\n")
          print("Volte sempre!\n")
          break
        break

      #Opção 5 - Cancelar compra
      elif op2 == 5:
        while True:
          sim_ou_nao = int(input('''Deseja realmente desistir da sua compra?
          [1] - Sim
          [2] - Não\n'''))

          #Confirma o cancelamento da compra e limpa o carrinho
          if sim_ou_nao == 1:
            carrinho_prod.clear()
            carrinho_prod_quant.clear()
            carrinho_prod_valor_total.clear()

            carrinho_serv.clear()
            carrinho_serv_quant.clear()
            carrinho_serv_valor_total.clear()
            print("Compra cancelada!")
            break

          #Exclusão do carrinho cancelada
          elif sim_ou_nao == 2:
            print("Obrigado por continuar comprando conosco!")
            break

          elif sim_ou_nao < 0 or sim_ou_nao > 2:
            print("Opção inválida")

      #Opção Inválida - Validação de opção
      else:
        print("Opção inválida.")